In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB #MultinomialNB
from sklearn.metrics import accuracy_score
#Binary: GaussianNB, Multi: MultinomialNB

In [3]:
# Load the Titanic dataset
titanic_df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
titanic_df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [4]:
titanic_df.shape

(891, 12)

In [5]:
titanic_df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [6]:
# Fill missing values in 'Age' column with mean/median age
titanic_df['Age'].fillna(titanic_df['Age'].median(), inplace=True)

In [7]:
# Fill missing values in 'Embarked' column with most frequent value
titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0], inplace=True)

In [8]:
# Preprocessing
# Drop irrelevant columns and columns with many missing values
titanic_df = titanic_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [9]:
titanic_df.shape

(891, 8)

In [10]:
titanic_df["Sex"]=titanic_df["Sex"].map({"male":0,"female":1})

In [11]:
titanic_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    0  22.0      1      0   7.2500        S
1         1       1    1  38.0      1      0  71.2833        C
2         1       3    1  26.0      0      0   7.9250        S
3         1       1    1  35.0      1      0  53.1000        S
4         0       3    0  35.0      0      0   8.0500        S

In [12]:
# Either you create or dummies OR make categories numerical
# Emabarked --> S/C/Q --> 0/1,2
# Label Encoding --> Ordinal Categorical Variable OR When we have huge number of categories
# One hot Encoding/Dummy Creation --> Non-Ordinal Categorical Variable OR When we have less number of categories

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
titanic_df['Embarked'] = le.fit_transform(titanic_df['Embarked'])

In [14]:
titanic_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         2
1         1       1    1  38.0      1      0  71.2833         0
2         1       3    1  26.0      0      0   7.9250         2
3         1       1    1  35.0      1      0  53.1000         2
4         0       3    0  35.0      0      0   8.0500         2

In [15]:
# Split the data into features and target variable
X = titanic_df.drop('Survived', axis=1)
y = titanic_df['Survived']

In [16]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
X_train.shape

(623, 7)

In [18]:
X_test.shape

(268, 7)

In [19]:
X_train.head(2)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
445       1    0   4.0      0      2  81.8583         2
650       3    0  28.0      0      0   7.8958         2

In [20]:
X_test.head(2)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
709       3    0  28.0      1      1  15.2458         0
439       2    0  31.0      0      0  10.5000         2

In [21]:
y_train.unique()

array([1, 0])

In [22]:
# Initialize the Naive Bayes classifier
nb_classifier = GaussianNB()

In [23]:
# Train the Naive Bayes classifier
nb_classifier.fit(X_train, y_train)

GaussianNB()

In [24]:
# Make predictions on the training and testing set
y_pred_train = nb_classifier.predict(X_train)
y_pred_test = nb_classifier.predict(X_test)

In [25]:
y_pred_train

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

In [26]:
nb_classifier.predict_proba(X_train)

array([[2.20727752e-01, 7.79272248e-01],
       [9.63987339e-01, 3.60126609e-02],
       [2.14434340e-01, 7.85565660e-01],
       ...,
       [9.90623372e-01, 9.37662776e-03],
       [7.70102977e-04, 9.99229897e-01],
       [3.58479289e-01, 6.41520711e-01]])

In [27]:
# Calculate the accuracy of the model
accuracy_train = accuracy_score(y_train, y_pred_train)
print("Train Accuracy: ",round(accuracy_train*100,2))
accuracy_test = accuracy_score(y_test, y_pred_test)
print("Test Accuracy: ",round(accuracy_test*100,2))

Train Accuracy:  79.13
Test Accuracy:  79.85


In [ ]:
# Calculate other evaluation metrices --> Precision/Recall/F1-Score